export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;

export const TODO_LIST_ID = process.env.NEXT_PUBLIC_APPWRITE_TODO_LIST_ID!;

export const COUNTDOWN_ID = process.env.NEXT_PUBLIC_APPWRITE_COUNTDOWN_ID!;

export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
